// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    public enum CapacitySettingsModel_Root_Metric {
        [EnumMember(Value = "Total")]
        Total,
        [EnumMember(Value = "Billable")]
        Billable,
    }
}
