// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    public enum CompanyModel_Root_EstimationModel {
        [EnumMember(Value = "JOB_PERSON_MONTH")]
        JOB_PERSON_MONTH,
        [EnumMember(Value = "JOB_MONTH")]
        JOB_MONTH,
        [EnumMember(Value = "JOB")]
        JOB,
        [EnumMember(Value = "JOB_PERSON")]
        JOB_PERSON,
        [EnumMember(Value = "FORECASTING")]
        FORECASTING,
        [EnumMember(Value = "JOB_TASK")]
        JOB_TASK,
    }
}
