// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    public enum ActionModelRequestAction_Action {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Submit")]
        Submit,
        [EnumMember(Value = "Approve")]
        Approve,
        [EnumMember(Value = "Reject")]
        Reject,
        [EnumMember(Value = "Cancel")]
        Cancel,
    }
}
