// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    /// <summary>  User requirements:Security Level(s): Admin, Manager (View Clients)Security Level(s): Admin, Manager (View Billingrates)  Company requirements:Billing rate model(s): User x Client</summary>
    public enum ClientModel_New_SecondaryBillingRateMode {
        [EnumMember(Value = "INHERIT")]
        INHERIT,
        [EnumMember(Value = "CUSTOM")]
        CUSTOM,
        [EnumMember(Value = "FLAT")]
        FLAT,
    }
}
