// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    public enum CompanyModel_Root_TimesheetModel {
        [EnumMember(Value = "monthly")]
        Monthly,
        [EnumMember(Value = "semimonthly")]
        Semimonthly,
        [EnumMember(Value = "biweekly")]
        Biweekly,
        [EnumMember(Value = "weekly")]
        Weekly,
        [EnumMember(Value = "custom")]
        Custom,
    }
}
