// <auto-generated/>
using ClickTime.NET.Internal.TimeEntry.AutoFill;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ClickTime.NET.Internal.TimeEntry {
    /// <summary>
    /// Builds and executes requests for operations under \Internal\TimeEntry
    /// </summary>
    public class TimeEntryRequestBuilder : BaseRequestBuilder {
        /// <summary>The AutoFill property</summary>
        public AutoFillRequestBuilder AutoFill { get =>
            new AutoFillRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new TimeEntryRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeEntryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Internal/TimeEntry", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new TimeEntryRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeEntryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Internal/TimeEntry", rawUrl) {
        }
    }
}
