// <auto-generated/>
using ClickTime.NET.Me.TimeOffTypes.Item.FutureBalance.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ClickTime.NET.Me.TimeOffTypes.Item.FutureBalance {
    /// <summary>
    /// Builds and executes requests for operations under \Me\TimeOffTypes\{timeOffTypeID}\FutureBalance
    /// </summary>
    public class FutureBalanceRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the ClickTime.NET.Me.TimeOffTypes.item.FutureBalance.item collection</summary>
        /// <param name="position">    Required</param>
        public WithDateItemRequestBuilder this[DateTimeOffset position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("date", position);
            return new WithDateItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the ClickTime.NET.Me.TimeOffTypes.item.FutureBalance.item collection</summary>
        /// <param name="position">    Required</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithDateItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("date", position);
            return new WithDateItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new FutureBalanceRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FutureBalanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Me/TimeOffTypes/{timeOffTypeID}/FutureBalance", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new FutureBalanceRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FutureBalanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Me/TimeOffTypes/{timeOffTypeID}/FutureBalance", rawUrl) {
        }
    }
}
