// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public class AllocationModel_Root : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This is calculated using the specified user and/or job according to your company&apos;s billing rate model.  User requirements:Security Level(s): Admin, Manager (View Billingrates)</summary>
        public double? EstBillingRate { get; set; }
        /// <summary>This is the current hourly &quot;CostRate&quot; for the specified user.  User requirements:Security Level(s): Admin, Manager (View Costs)</summary>
        public double? EstCostRate { get; set; }
        /// <summary>The EstHours property</summary>
        public double? EstHours { get; set; }
        /// <summary>  Request requirements:Verbose=true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ClickTime.NET.Generated.Models.Get.BasicJobModel_Job_Get.AllocationModel_Root? Job { get; set; }
#nullable restore
#else
        public ClickTime.NET.Generated.Models.Get.BasicJobModel_Job_Get.AllocationModel_Root Job { get; set; }
#endif
        /// <summary>The JobID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobID { get; set; }
#nullable restore
#else
        public string JobID { get; set; }
#endif
        /// <summary>The Month property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Month { get; set; }
#nullable restore
#else
        public string Month { get; set; }
#endif
        /// <summary>  Request requirements:Verbose=true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ClickTime.NET.Generated.Models.Get.BasicUserModel_User_Get.AllocationModel_Root? User { get; set; }
#nullable restore
#else
        public ClickTime.NET.Generated.Models.Get.BasicUserModel_User_Get.AllocationModel_Root User { get; set; }
#endif
        /// <summary>The UserID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserID { get; set; }
#nullable restore
#else
        public string UserID { get; set; }
#endif
        /// <summary>
        /// Instantiates a new AllocationModel_Root and sets the default values.
        /// </summary>
        public AllocationModel_Root() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AllocationModel_Root CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AllocationModel_Root();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"EstBillingRate", n => { EstBillingRate = n.GetDoubleValue(); } },
                {"EstCostRate", n => { EstCostRate = n.GetDoubleValue(); } },
                {"EstHours", n => { EstHours = n.GetDoubleValue(); } },
                {"Job", n => { Job = n.GetObjectValue<ClickTime.NET.Generated.Models.Get.BasicJobModel_Job_Get.AllocationModel_Root>(ClickTime.NET.Generated.Models.Get.BasicJobModel_Job_Get.AllocationModel_Root.CreateFromDiscriminatorValue); } },
                {"JobID", n => { JobID = n.GetStringValue(); } },
                {"Month", n => { Month = n.GetStringValue(); } },
                {"User", n => { User = n.GetObjectValue<ClickTime.NET.Generated.Models.Get.BasicUserModel_User_Get.AllocationModel_Root>(ClickTime.NET.Generated.Models.Get.BasicUserModel_User_Get.AllocationModel_Root.CreateFromDiscriminatorValue); } },
                {"UserID", n => { UserID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("EstBillingRate", EstBillingRate);
            writer.WriteDoubleValue("EstCostRate", EstCostRate);
            writer.WriteDoubleValue("EstHours", EstHours);
            writer.WriteObjectValue<ClickTime.NET.Generated.Models.Get.BasicJobModel_Job_Get.AllocationModel_Root>("Job", Job);
            writer.WriteStringValue("JobID", JobID);
            writer.WriteStringValue("Month", Month);
            writer.WriteObjectValue<ClickTime.NET.Generated.Models.Get.BasicUserModel_User_Get.AllocationModel_Root>("User", User);
            writer.WriteStringValue("UserID", UserID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
