// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public class EmploymentTypeModel_New : IAdditionalDataHolder, IParsable {
        /// <summary>  User requirements:Security Level(s): Admin, Manager (View Employment Types)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountingPackageID { get; set; }
#nullable restore
#else
        public string AccountingPackageID { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>  Request requirements:Verbose=true  Company requirements:Leave Type Restrictions: By Employment Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AlternativeTimeOffTypeIDs { get; set; }
#nullable restore
#else
        public List<string> AlternativeTimeOffTypeIDs { get; set; }
#endif
        /// <summary>  Request requirements:Verbose=true  Company requirements:Leave Type Restrictions: By Employment Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? HolidayTypeIDs { get; set; }
#nullable restore
#else
        public List<string> HolidayTypeIDs { get; set; }
#endif
        /// <summary>The ID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ID { get; set; }
#nullable restore
#else
        public string ID { get; set; }
#endif
        /// <summary>The IsActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>  User requirements:Security Level(s): Admin, Manager (View Employment Types)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>  Request requirements:Verbose=true  Company requirements:Leave Type Restrictions: By Employment Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TimeOffTypeIDs { get; set; }
#nullable restore
#else
        public List<string> TimeOffTypeIDs { get; set; }
#endif
        /// <summary>  Request requirements:Verbose=true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ClickTime.NET.Generated.Models.Get.BasicUserModel_Users_Get.EmploymentTypeModel_New>? Users { get; set; }
#nullable restore
#else
        public List<ClickTime.NET.Generated.Models.Get.BasicUserModel_Users_Get.EmploymentTypeModel_New> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new EmploymentTypeModel_New and sets the default values.
        /// </summary>
        public EmploymentTypeModel_New() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static EmploymentTypeModel_New CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new EmploymentTypeModel_New();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"AccountingPackageID", n => { AccountingPackageID = n.GetStringValue(); } },
                {"AlternativeTimeOffTypeIDs", n => { AlternativeTimeOffTypeIDs = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"HolidayTypeIDs", n => { HolidayTypeIDs = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"ID", n => { ID = n.GetStringValue(); } },
                {"IsActive", n => { IsActive = n.GetBoolValue(); } },
                {"Name", n => { Name = n.GetStringValue(); } },
                {"Notes", n => { Notes = n.GetStringValue(); } },
                {"TimeOffTypeIDs", n => { TimeOffTypeIDs = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"Users", n => { Users = n.GetCollectionOfObjectValues<ClickTime.NET.Generated.Models.Get.BasicUserModel_Users_Get.EmploymentTypeModel_New>(ClickTime.NET.Generated.Models.Get.BasicUserModel_Users_Get.EmploymentTypeModel_New.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountingPackageID", AccountingPackageID);
            writer.WriteCollectionOfPrimitiveValues<string>("AlternativeTimeOffTypeIDs", AlternativeTimeOffTypeIDs);
            writer.WriteCollectionOfPrimitiveValues<string>("HolidayTypeIDs", HolidayTypeIDs);
            writer.WriteStringValue("ID", ID);
            writer.WriteBoolValue("IsActive", IsActive);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("Notes", Notes);
            writer.WriteCollectionOfPrimitiveValues<string>("TimeOffTypeIDs", TimeOffTypeIDs);
            writer.WriteCollectionOfObjectValues<ClickTime.NET.Generated.Models.Get.BasicUserModel_Users_Get.EmploymentTypeModel_New>("Users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
