// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public enum NotificationModel_Root_NotificationType {
        [EnumMember(Value = "RemindComplete")]
        RemindComplete,
        [EnumMember(Value = "NotifyIncomplete")]
        NotifyIncomplete,
        [EnumMember(Value = "RemindSubmit")]
        RemindSubmit,
        [EnumMember(Value = "NotifyUnsubmitted")]
        NotifyUnsubmitted,
        [EnumMember(Value = "RemindOrNotifyTimeRequirement")]
        RemindOrNotifyTimeRequirement,
        [EnumMember(Value = "NotifyApprove")]
        NotifyApprove,
    }
}
