// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    /// <summary>The availability of this permission (e.g. All, or restricted by Division).</summary>
    public enum PermissionModel_AccessLevel {
        [EnumMember(Value = "All")]
        All,
        [EnumMember(Value = "Divisions")]
        Divisions,
        [EnumMember(Value = "Projects")]
        Projects,
    }
}
