// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public enum TimeOffRequestModel_Manage_Status {
        [EnumMember(Value = "Submitted")]
        Submitted,
        [EnumMember(Value = "Approved")]
        Approved,
        [EnumMember(Value = "Rejected")]
        Rejected,
        [EnumMember(Value = "Cancelled")]
        Cancelled,
    }
}
