// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public class TimeOffTypeModel_New : IAdditionalDataHolder, IParsable {
        /// <summary>  User requirements:Security Level(s): Admin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountingPackageID { get; set; }
#nullable restore
#else
        public string AccountingPackageID { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>  User requirements:Security Level(s): Admin  Company requirements:Custom Fields must be configured for TimeOffType.Custom Fields on Leave Types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public TimeOffTypeModel_New_CustomFields? CustomFields { get; set; }
#nullable restore
#else
        public TimeOffTypeModel_New_CustomFields CustomFields { get; set; }
#endif
        /// <summary>  User requirements:Security Level(s): Admin  Company requirements:Optional module(s): Time Off Management</summary>
        public double? DefaultAccrualRate { get; set; }
        /// <summary>  User requirements:Security Level(s): Admin  Company requirements:Optional module(s): Time Off Management</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultApproverID { get; set; }
#nullable restore
#else
        public string DefaultApproverID { get; set; }
#endif
        /// <summary>  User requirements:Security Level(s): Admin  Company requirements:Optional module(s): Time Off Management</summary>
        public double? DefaultMaximumBalance { get; set; }
        /// <summary>  User requirements:Security Level(s): Admin</summary>
        public double? DefaultStartingBalance { get; set; }
        /// <summary>  Company requirements:Optional module(s): Time Off ManagementCanViewWorkTypeBalanceDashboard</summary>
        public bool? DisplayOnTimeEntryPages { get; set; }
        /// <summary>  Request requirements:Verbose=true  Company requirements:Leave Type Restrictions: By Employment Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EmploymentTypeIDs { get; set; }
#nullable restore
#else
        public List<string> EmploymentTypeIDs { get; set; }
#endif
        /// <summary>The ID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ID { get; set; }
#nullable restore
#else
        public string ID { get; set; }
#endif
        /// <summary>The IsActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The Notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The RequiresApproval property</summary>
        public bool? RequiresApproval { get; set; }
        /// <summary>
        /// Instantiates a new TimeOffTypeModel_New and sets the default values.
        /// </summary>
        public TimeOffTypeModel_New() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static TimeOffTypeModel_New CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new TimeOffTypeModel_New();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"AccountingPackageID", n => { AccountingPackageID = n.GetStringValue(); } },
                {"CustomFields", n => { CustomFields = n.GetObjectValue<TimeOffTypeModel_New_CustomFields>(TimeOffTypeModel_New_CustomFields.CreateFromDiscriminatorValue); } },
                {"DefaultAccrualRate", n => { DefaultAccrualRate = n.GetDoubleValue(); } },
                {"DefaultApproverID", n => { DefaultApproverID = n.GetStringValue(); } },
                {"DefaultMaximumBalance", n => { DefaultMaximumBalance = n.GetDoubleValue(); } },
                {"DefaultStartingBalance", n => { DefaultStartingBalance = n.GetDoubleValue(); } },
                {"DisplayOnTimeEntryPages", n => { DisplayOnTimeEntryPages = n.GetBoolValue(); } },
                {"EmploymentTypeIDs", n => { EmploymentTypeIDs = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"ID", n => { ID = n.GetStringValue(); } },
                {"IsActive", n => { IsActive = n.GetBoolValue(); } },
                {"Name", n => { Name = n.GetStringValue(); } },
                {"Notes", n => { Notes = n.GetStringValue(); } },
                {"RequiresApproval", n => { RequiresApproval = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountingPackageID", AccountingPackageID);
            writer.WriteObjectValue<TimeOffTypeModel_New_CustomFields>("CustomFields", CustomFields);
            writer.WriteDoubleValue("DefaultAccrualRate", DefaultAccrualRate);
            writer.WriteStringValue("DefaultApproverID", DefaultApproverID);
            writer.WriteDoubleValue("DefaultMaximumBalance", DefaultMaximumBalance);
            writer.WriteDoubleValue("DefaultStartingBalance", DefaultStartingBalance);
            writer.WriteBoolValue("DisplayOnTimeEntryPages", DisplayOnTimeEntryPages);
            writer.WriteCollectionOfPrimitiveValues<string>("EmploymentTypeIDs", EmploymentTypeIDs);
            writer.WriteStringValue("ID", ID);
            writer.WriteBoolValue("IsActive", IsActive);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("Notes", Notes);
            writer.WriteBoolValue("RequiresApproval", RequiresApproval);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
