// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    /// <summary>  User requirements:Security Level(s): Admin, Manager (View People for all Divisions)</summary>
    public enum UserModel_Root_PreferredTimeFormat {
        [EnumMember(Value = "24Hour")]
        TwoFourHour,
        [EnumMember(Value = "AMPM")]
        AMPM,
    }
}
