// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    /// <summary>  User requirements:Security Level(s): Admin, Manager (Review timesheets using a WithPermission filter), Manager (View People for all Divisions)</summary>
    public enum UserModel_Root_MinimumTimePeriod {
        [EnumMember(Value = "Day")]
        Day,
        [EnumMember(Value = "Week")]
        Week,
    }
}
