// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Get {
    public enum UserModel_Manage_PreferredTimeFormat {
        [EnumMember(Value = "24Hour")]
        TwoFourHour,
        [EnumMember(Value = "AMPM")]
        AMPM,
    }
}
