// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Patch {
    public enum UserModel_Manage_PreferredTimeFormat {
        [EnumMember(Value = "24hour")]
        TwoFourhour,
        [EnumMember(Value = "AMPM")]
        AMPM,
    }
}
