// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Post {
    /// <summary>  User requirements:Security Level(s): Admin, Manager (Add/Edit Costs)  Company requirements:Salaried Costs</summary>
    public enum UserModel_Root_CostModel {
        [EnumMember(Value = "Hourly")]
        Hourly,
        [EnumMember(Value = "Salary")]
        Salary,
    }
}
