// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Post {
    public enum TimeOffRequestActionModel_Manage_Action {
        [EnumMember(Value = "Approve")]
        Approve,
        [EnumMember(Value = "Reject")]
        Reject,
    }
}
