// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Generated.Models.Post {
    /// <summary>  User requirements:Security Level(s): Admin</summary>
    public enum UserModel_Root_SecurityLevel {
        [EnumMember(Value = "STANDARD")]
        STANDARD,
        [EnumMember(Value = "MANAGER")]
        MANAGER,
    }
}
