// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Post {
    public enum UserModel_Root_PreferredTimeEntryView {
        [EnumMember(Value = "ClassicDayView")]
        ClassicDayView,
        [EnumMember(Value = "DayView")]
        DayView,
        [EnumMember(Value = "WeekView")]
        WeekView,
    }
}
