// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Patch {
    public enum CompanyModel_Root_CurrencyFormat {
        [EnumMember(Value = "Symbol")]
        Symbol,
        [EnumMember(Value = "ISO")]
        ISO,
    }
}
