// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Patch {
    public enum UserModel_Me_JobSelectionMethod {
        [EnumMember(Value = "DROP_DOWN_LIST")]
        DROP_DOWN_LIST,
        [EnumMember(Value = "TYPE_AHEAD")]
        TYPE_AHEAD,
    }
}
