// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get.BasicAlternativeTimeOffTypeModel_AlternativeTimeOffType_Get {
    public enum AlternativeTimeOffEntryModel_Me_Type {
        [EnumMember(Value = "external")]
        External,
        [EnumMember(Value = "holiday")]
        Holiday,
    }
}
