// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClickTime.NET.Models.Get {
    public enum ExpenseSheetModel_Root_Status {
        [EnumMember(Value = "open")]
        Open,
        [EnumMember(Value = "approved")]
        Approved,
        [EnumMember(Value = "rejected")]
        Rejected,
        [EnumMember(Value = "waiting")]
        Waiting,
        [EnumMember(Value = "paid")]
        Paid,
    }
}
