// <auto-generated/>
using ClickTime.NET.Generated.Internal.MyRecents.TaskNamespace.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ClickTime.NET.Generated.Internal.MyRecents.TaskNamespace {
    /// <summary>
    /// Builds and executes requests for operations under \Internal\MyRecents\Task
    /// </summary>
    public class TaskRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the ClickTime.NET.Generated.Internal.MyRecents.Task.item collection</summary>
        /// <param name="position">    Required</param>
        public WithTaskItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("taskID", position);
            return new WithTaskItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new TaskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Internal/MyRecents/Task", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new TaskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Internal/MyRecents/Task", rawUrl) {
        }
    }
}
